local type
local cute, cool, sexy = "pop", "Cute", "Cool", "Sexy", "Pop"


return setmetatable({
	{
		{"name", "星宮 いちご"},
		name_rm = "Ichigo",
		{"actor", "諸星 すみれ"},
		{"birthday", "3/15"},
		{"zodiac_sign", "Picces"},
		{"blood_type", "O"},
		{"favorite_brand", "Angely Sugar"},
		{"type", cute},
		{"signature_songs", {"輝きのエチュード", "Growing for a dream", "Dance in the rain"}},
		{"sing", "霧島 若歌"},
		{"belonging_to", {"Soleil", "STAR☆ANIS", "2wingS"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "霧矢 あおい"},
		name_rm = "Aoi",
		{"actor", "田所 あずさ"},
		{"birthday", "1/31"},
		{"zodiac_sign", "Aquarius"},
		{"blood_type", "A"},
		{"favorite_brand", "FUTURING GIRL"},
		{"type", cool},
		{"signature_songs", {"prism spiral", "Stranger alien"}},
		{"sing", "上花 風裏"},
		{"belonging_to", {"Soleil", "STAR☆ANIS"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "紫吹 蘭"},
		name_rm = "Ran",
		{"actor", "大橋 彩香"},
		{"birthday", "8/3"},
		{"zodiac_sign", "Leo"},
		{"blood_type", "AB"},
		{"favorite_brand", "SPICY AGEHA"},
		{"type", sexy},
		{"signature_songs", {"Trap of Love"}},
		{"sing", "市倉 有菜"},
		{"belonging_to", {"Soleil", "Tristar", "STAR☆ANIS"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "神谷 しおん"},
		name_rm = "Shion",
		{"actor", "瀬戸 麻沙美"},
		{"birthday", "1/11"},
		{"zodiac_sign", "Capricorn"},
		{"blood_type", "A"},
		{"favorite_brand", "FUTURING GIRL"},
		{"type", cool},
		{"belonging_to", {"ぽわぽわプリリン"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "有栖川 おとめ"},
		name_rm = "Otome",
		{"actor", "黒沢 ともよ"},
		{"birthday", "5/5"},
		{"zodiac_sign", "Taurus"},
		{"blood_type", "B"},
		{"favorite_brand", "HAPPY RAINBOW"},
		{"type", pop},
		{"signature_songs", {"Angel Snow", "放課後ポニーテール", "CHU-CHU RAINBOW"}},
		{"sing", "美谷 玲美"},
		{"belonging_to", {"ぽわぽわプリリン", "STAR☆ANIS"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "藤堂 ユリカ"},
		name_rm = "Yurika",
		{"actor", "沼倉 愛美"},
		{"birthday", "12/26"},
		{"zodiac_sign", "Capricorn"},
		{"blood_type", "B"},
		{"favorite_brand", "LoLi GoThiC"},
		{"type", cool},
		{"signature_songs", {"硝子ドール", "永遠の灯"}},
		{"sing", "美谷 玲美"},
		{"belonging_to", {"Tristar", "STAR☆ANIS"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "北大路 さくら"},
		name_rm = "Sakura",
		{"actor", "安野 希世乃"},
		{"birthday", "4/6"},
		{"zodiac_sign", "Aries"},
		{"blood_type", "A"},
		{"favorite_brand", "Aurora Fantasy"},
		{"type", cute},
		{"signature_songs", {"同じ地球のしあわせに"}},
		{"belonging_to", {"ぽわぽわプリリン", "STAR☆ANIS"}},
		{"sing", "愛野 えり"},
		{"school", "スターライト学園"},
		{"pet", {"koiichi", "koini", "koisan", "koishi", "koigo", "koiroku"}},
	},
	{
		{"name", "一ノ瀬 かえで"},
		name_rm = "Kaede",
		{"actor", "三村 ゆうな"},
		{"birthday", "11/23"},
		{"zodiac_sign", "Sagittarius"},
		{"blood_type", "O"},
		{"favorite_brand", "MAGICAL TOY"},
		{"type", pop},
		{"sing", "市倉 有菜"},
		{"belonging_to", {"Tristar", "STAR☆ANIS"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "三ノ輪 ヒカリ"},
		name_rm = "Hikari",
		{"actor", "森谷 里美"},
		{"birthday", "3/28"},
		{"zodiac_sign", "Aries"},
		{"blood_type", "AB"},
		{"favorite_brand", "SPICY AGEHA"},
		{"type", sexy},
		{"sing", "森下 ゆにこ"},
		{"school", "スターライト学園"},
	},
	{
		{"name", "大空 あかり"},
		name_rm = "Akari",
		{"actor", "下地 柴野"},
		{"birthday", "4/1"},
		{"zodiac_sign", "Aries"},
		{"blood_type", "A"},
		{"favorite_brand", "Dreamy Crown"},
		{"type", cute},
		{"signature_songs", {}},
		{"sing", "遠藤 瑠香"},
		{"belonging_to", {"GOGO! いちご応援隊"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "氷上 スミレ"},
		name_rm = "Sumire",
		{"actor", "和久井 優"},
		{"birthday", "10/20"},
		{"zodiac_sign", "Libra"},
		{"blood_type", "AB"},
		{"favorite_brand", "LoLi GoThiC"},
		{"type", cool},
		{"signature_songs", {"タルト･タタン"}},
		{"sing", "巴山 萌菜"},
		{"belonging_to", {"GOGO! いちご応援隊"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "新条 ひなき"},
		name_rm = "Hinaki",
		{"actor", "石川 由依"},
		{"birthday", "6/11"},
		{"zodiac_sign", "Gemini"},
		{"blood_type", "B"},
		{"favorite_brand", "ViVid Kiss"},
		{"type", pop},
		{"sing", "みき"},
		{"belonging_to", {"GOGO! いちご応援隊"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "紅林 珠璃"},
		name_rm = "Juri",
		{"actor", "斎藤 綾"},
		{"birthday", "7/31"},
		{"zodiac_sign", "Leo"},
		{"blood_type", "O"},
		{"favorite_brand", "Sangria Rosa"},
		{"type", sexy},
		{"signature_songs", {"Passion Flower"}},
		{"sing", "みほ"},
		{"school", "スターライト学園"},
	},

	-- Dream Academy
	{
		{"name", "音城 セイラ"},
		name_rm = "Seira",
		{"actor", "石原 夏織"},
		{"birthday", "11/11"},
		{"zodiac_sign", "Scorpio"},
		{"blood_type", "A"},
		{"favorite_brand", "Swing ROCK"},
		{"type", cool},
		{"sing", "上花 風裏"},
		{"belonging_to", {"2wingS"}},
		{"school", "ドリーム・アカデミー"},
	},
	{
		{"name", "冴草 きい"},
		name_rm = "Kii",
		{"actor", "秋奈"},
		{"birthday", "12/3"},
		{"zodiac_sign", "Sagittarius"},
		{"blood_type", "O"},
		{"favorite_brand", "MAGICAL TOY"},
		{"type", pop},
		{"signature_songs", {"マジカルタイム"}},
		{"sing", "市倉 有菜"},
		{"school", "ドリーム・アカデミー"},
	},
	{
		{"name", "風沢 そら"},
		name_rm = "Sora",
		{"actor", "高橋 未奈美"},
		{"birthday", "10/2"},
		{"zodiac_sign", "Libra"},
		{"blood_type", "B"},
		{"favorite_brand", "Bohemian Sky"},
		{"type", sexy},
		{"signature_songs", {"Kira･pata･shining"}},
		{"sing", "愛野 えり"},
		{"school", "ドリーム・アカデミー"},
		{"pet", "パーム"},
	},
	{
		{"name", "姫里 マリア"},
		name_rm = "Maria",
		{"actor", "冨岡 美沙子"},
		{"birthday", "4/18"},
		{"zodiac_sign", "Virgo"},
		{"blood_type", "O"},
		{"favorite_brand", "Aurora Fantasy"},
		{"type", cute},
		{"signature_songs", {"オーロラプリンセス"}},
		{"sing", "愛野 えり"},
		{"school", "ドリーム・アカデミー"},
		{"pet", "エリザベス三世"},
	},

	-- other
	{
		{"name", "神崎 美月"},
		name_rm = "Mizuki",
		{"actor", "寿 美菜子"},
		{"birthday", "9/18"},
		{"zodiac_sign", "Virgo"},
		{"blood_type", "A"},
		{"favorite_brand", "LOVE MOONRISE"},
		{"type", sexy},
		{"signature_songs", {"Move on now!", "Moonlight destiny", "Precious"}},
		{"sing", "ささかま リス子"},
		{"belonging_to", {"Tristar", "STAR☆ANIS", "WM"}},
	},
	{
		{"name", "夏樹 みくる"},
		name_rm = "Mikuru",
		{"actor", "洲崎 綾"},
		{"birthday", "7/7"},
		{"zodiac_sign", "Cancer"},
		{"blood_type", "O"},
		{"favorite_brand", "ViVid Kiss"},
		{"type", pop},
		{"signature_songs", {"オトナモード"}},
		{"sing", "巴山 萌菜"},
		{"belonging_to", {"WM"}},
		{"pet", "フェレッ太"},
	}
}, {__mode = "k"})

