#!/bin/bash

ver=$(lua -luakatsu -e print\(Aikatsu.version\))

cat <<EOF
# luakatsu (Lua + Aikastu) ${ver}
[Rubicure](https://github.com/sue445/rubicure) is **Ruby + Precure**, it is **Lua + [Aikastu](http://aikatsu.wikia.com/wiki/Aikatsu_Wiki)**

## install
\`luarocks --local install luakatsu\`

or

\`luarocks --local --from=https://github.com/Nymphium/luakatsu/raw/master/ install luakatsu\`

or

\`\`\`sh
git clone https://github.com/Nymphium/luakatsu
cd luakatsu
luarocks --local make
\`\`\`


## compatibility
after v1.3, non-idol characters' data is nothing here.
	and catchphrase is not supported.

## usage
\`\`\`
$ lua

> require "luakatsu"
> print(type(Aikatsu))
table
> print(Aikatsu.version)
${ver}
\`\`\`

### local table (\`version >= v2.1-1\`)
\`local luakatsu = require "luakatsu.local"\`

### profile

\`\`\`lua
print(Aikatsu.Ichigo.name) ---> 星宮 いちご

print(table.concat(Aikastu.Ichigo.signature_songs), ", ") ---> $(lua -luakatsu -e "print(table.concat(Aikatsu.Ichigo.signature_songs, \", \"))")

Aikatsu.Ichigo()

--[[
$(lua -luakatsu -e Aikatsu.Ichigo\(\))
--]]

\`\`\`

### groups
\`\`\`lua
Aikatsu.groups.Soleil()

--[[
$(lua -luakatsu -e "Aikatsu.groups.Soleil()")
--]]
\`\`\`


### one-liner
\`\`\`
$ lua -luakatsu -e Aikatsu\(\)
$(lua -luakatsu -e Aikatsu\(\))
\`\`\`


## License
MIT License

EOF

