#!/usr/bin/bash

ver=${1}

if [[ "${ver}" = "-h" ]] || [[ "${ver}" = "" ]] ; then
	cat "${0}"
	exit 0
fi

luarocks write_rockspec luakatsu "${ver}" . \
	--license="MIT" \
	--summary="Aikatsu! --- Idol KATSUDOU, with Lua" \
	--homepage="https://github.com/Nymphium/luakatsu/" \
	--lua-version=5.2,5.3 \
	--detailed="Let's Aikatsu! with Lua!!" \
	--tag="v${ver}"

