local tag = require "luakatsu/bin/tag"

return setmetatable({
	{
		tag(1, "星宮 いちご"), name_rm = "Ichigo",
		tag(2, "諸星 すみれ"),
		tag(4 , 3),
		tag(5 , "のり弁"),
		tag(6 , "ご飯をきっちりよそう"),
		tag(7 , "Angely Sugar"),
		tag(8 , 1),
		tag(9 , {"輝きのエチュード", "Growing for a dream", "Dance in the rain"}),
		tag(10 , "霧島 若歌"),
		tag(11 , "Soleil", "STAR☆ANIS", "2wingS"),
		tag(12 , 1),
		tag(3 , "03/15"),
	},
	{
		tag(1, "霧矢 あおい"), name_rm = "Aoi",
		tag(2, "田所 あずさ"),
		tag(4, 1),
		tag(5, "サンドイッチ"),
		tag(6, "一目見たアイドルは忘れない"),
		tag(7, "FUTURING GIRL"),
		tag(8, 4),
		tag(9, {"prism spiral", "Stranger alien"}),
		tag(10, "上花 風裏"),
		tag(11, "Soleil", "STAR☆ANIS"),
		tag(12, 1),
		tag(3, "01/31"),
	},
	{
		tag(1, "紫吹 蘭"), name_rm = "Ran",
		tag(2, "大橋 彩香"),
		tag(4, 4),
		tag(5, "野菜スティック", "ヨーグルト"),
		tag(6, "ウォーキング", "ポージング"),
		tag(7, "SPICY AGEHA"),
		tag(8, 3),
		tag(9, {"Trap of Love"}),
		tag(10, "市倉 有菜"),
		tag(11, "Soleil", "Tristar", "STAR☆ANIS"),
		tag(12, 1),
		tag(3, "08/03"),
	},
	{
		tag(1, "神谷 しおん"), name_rm = "Shion",
		tag(2, "瀬戸 麻沙美"),
		tag(4, 1),
		tag(5, "ガトーショコラ"),
		tag(7, "FUTURING GIRL"),
		tag(8, 4),
		tag(11, "Powa²×PuRiRiN"),
		tag(12, 1),
		tag(3, "01/11"),
	},
	{
		tag(1, "有栖川 おとめ"), name_rm = "Otome",
		tag(2, "黒沢 ともよ"),
		tag(4, 2),
		tag(5, "ハンバーグ", "オムライス", "スパゲッティ", "エビフライ", "プリン"),
		tag(6, "動物のモノマネ"),
		tag(7, "HAPPY RAINBOW"),
		tag(8, 2),
		tag(9, {"Angel Snow", "放課後ポニーテール", "CHU-CHU RAINBOW"}),
		tag(10, "美谷 玲美"),
		tag(11, "Powa²×PuRiRiN", "STAR☆ANIS"),
		tag(12, 1),
		tag(3, "05/05"),
	},
	{
		tag(1, "藤堂 ユリカ"), name_rm = "Yurika",
		tag(2, "沼倉 愛美"),
		tag(4, 2),
		tag(5, "牛丼", "ラーメン"),
		tag(6, "水泳"),
		tag(7, "LoLi GoThiC"),
		tag(8, 4),
		tag(9, {"硝子ドール", "永遠の灯"}),
		tag(10, "美谷 玲美"),
		tag(11, "Tristar", "STAR☆ANIS"),
		tag(12, 1),
		tag(3, "12/26"),
	},
	{
		tag(1, "北大路 さくら"), name_rm = "Sakura",
		tag(2, "安野 希世乃"),
		tag(4, 1),
		tag(5, "抹茶", "和菓子"),
		tag(6, "特に何も"),
		tag(7, "Aurora Fantasy"),
		tag(8, 1),
		tag(9, {"同じ地球のしあわせに"}),
		tag(10, "Powa²×PuRiRiN", "STAR☆ANIS"),
		tag(11, "愛野 えり"),
		tag(12, 1),
		tag("pets", "こいいち", "こいじ", "こいぞう", "こいし", "こいご", "こいろく", "こいしち", "こいはち", "こいきゅう", "こいじゅう"),
		tag(3, "04/06"),
	},
	{
		tag(1, "一ノ瀬 かえで"), name_rm = "Kaede",
		tag(2, "三村 ゆうな"),
		tag(4, 3),
		tag(5, "カリフォルニアロール", "ハンバーガー"),
		tag(6, "マジック", "ダンス全般"),
		tag(7, "MAGICAL TOY"),
		tag(8, 2),
		tag(10, "Tristar", "STAR☆ANIS"),
		tag(11, "市倉 有菜"),
		tag(12 , 1),
		tag(3, "11/23"),
	},
	{
		tag(1, "三ノ輪 ヒカリ"), name_rm = "Hikari",
		tag(2, "森谷 里美"),
		tag(4, 4),
		tag(5, "トロピカルジュース", "ロコモコ"),
		tag(7, "SPICY AGEHA"),
		tag(8, 3),
		tag(11, "森下 ゆにこ"),
		tag(12, 1),
		tag(3, "03/28"),
	},
	{
		tag(1, "大空 あかり"), name_rm = "Akari",
		tag(2, "下地 柴野"),
		tag(4, 1),
		tag(5, "スイカ", "チョコレート", "ドーナツ", "みかん", "カレー"),
		tag(6, "ものまね"),
		tag(7, "Dreamy Crown"),
		tag(8, 1),
		tag(9, {"Blooming♡Blooming"}),
		tag(10, "遠藤 瑠香"),
		tag(11, "GOGO! いちご応援隊", "Skips♪", "Luminas", "Luminas"),
		tag(12, 1),
		tag(3, "04/01"),
	},
	{
		tag(1, "氷上 スミレ"), name_rm = "Sumire",
		tag(2, "和久井 優"),
		tag(4, 4),
		tag(5, "紅茶", "スコーン"),
		tag(6, "タロット占い"),
		tag(7, "LoLi GoThiC"),
		tag(8, 4),
		tag(9, {"タルト･タタン", "エメラルドの魔法"}),
		tag(10, "巴山 萌菜"),
		tag(11, "GOGO! いちご応援隊", "Dancing Diva", "Luminas"),
		tag(12, 1),
		tag(3, "10/20"),
	},
	{
		tag(1, "新条 ひなき"), name_rm = "Hinaki",
		tag(2, "石川 由依"),
		tag(4, 2),
		tag(5, "ビタミンCドリンク", "グレープフルーツ", "アサイー"),
		tag(6, "美の追求", "情報収集", "新ブランドなどのニュース集め"),
		tag(7, "ViVid Kiss"),
		tag(8, 2),
		tag(10, "未来 みき"),
		tag(11, "GOGO! いちご応援隊", "情熱★ハラペーニョ", "Luminas"),
		tag(12, 1),
		tag(3, "06/11"),
	},
	{
		tag(1, "紅林 珠璃"), name_rm = "Juri",
		tag(2, "斎藤 綾"),
		tag(4, 3),
		tag(5, "生ハム", "パエリア"),
		tag(6, "フラメンコ", "バレエ"),
		tag(7, "Sangria Rosa"),
		tag(8, 3),
		tag(9, {"Passion Flower"}),
		tag(10, "天音 みほ"),
		tag(11, "情熱★ハラペーニョ", "バニラチリペッパー"),
		tag(12, 1),
		tag(3, "07/31"),
	},
	{
		tag(1, "黒沢 凛"), name_rm = "Rin",
		tag(2, "高田 憂希"),
		tag(4, 4),
		tag(5, "しらたまあんみつ", "からあげ"),
		tag(6, "ダンス"),
		tag(7, "Dance Fusion"),
		tag(8, 4),
		tag(9, {"MY SHOW TIME!"}),
		tag(10, "松岡 ななせ"),
		tag(11, "Dancing Diva", "バニラチリペッパー"),
		tag(12, 1),
		tag(3, "01/01"),
	},
	{
		tag(1, "天羽 まどか"), name_rm = "Madoka",
		tag(2, "川上 千尋"),
		tag(4, 3),
		tag(5, "チョコレート"),
		tag(6, "スマイル"),
		tag(7, "Angely Sugar"),
		tag(8, 1),
		tag(9, {"ハローニューワールド"}),
		tag(10, "星咲 花那"),
		tag(11, "Skips♪", "バニラチリペッパー"),
		tag(12, 1),
		tag(3, "02/14"),
	},

	-- Dream Academy
	{
		tag(1, "音城 セイラ"), name_rm = "Seira",
		tag(2, "石原 夏織"),
		tag(4, 1),
		tag(5, "パスタ", "コーヒーゼリー"),
		tag(6, "楽器全般"),
		tag(7, "Swing ROCK"),
		tag(8, 4),
		tag(10, "上花 風裏"),
		tag(11, "2wingS"),
		tag(12, 2),
		tag(3, "11/11"),
	},
	{
		tag(1, "冴草 きい"), name_rm = "Kii",
		tag(2, "秋奈"),
		tag(4, 3),
		tag(5, "ブレインサンダー"),
		tag(6, "パソコン"),
		tag(7, "MAGICAL TOY"),
		tag(8, 2),
		tag(9, {"マジカルタイム"}),
		tag(10, "市倉 有菜"),
		tag(12, 2),
		tag(3, "12/03"),
	},
	{
		tag(1, "風沢 そら"), name_rm = "Sora",
		tag(2, "高橋 未奈美"),
		tag(4, 2),
		tag(5, "エスニック料理全般"),
		tag(6, "ドレスデザイン", "一人旅"),
		tag(7, "Bohemian Sky"),
		tag(8, 3),
		tag(9, {"Kira･pata･shining"}),
		tag(10, "愛野 えり"),
		tag(12, 2),
		tag("pets", "パーム"),
		tag(3, "10/02"),
	},
	{
		tag(1, "姫里 マリア"), name_rm = "Maria",
		tag(2, "冨岡 美沙子"),
		tag(4, 3),
		tag(5, "ザッハトルテ"),
		tag(6, "違いのわかる女!"),
		tag(7, "Aurora Fantasy"),
		tag(8, 1),
		tag(9, {"オーロラプリンセス"}),
		tag(10, "愛野 えり"),
		tag(12, 2),
		tag("pets", "エリザベス三世"),
		tag(3, "04/18"),
	},

	-- other
	{
		tag(1, "神崎 美月"), name_rm = "Mizuki",
		tag(2, "寿 美菜子"),
		tag(4, 1),
		tag(5, "マロングラッセ", "香りの良い紅茶"),
		tag(6, "歌"),
		tag(7, "LOVE MOONRISE"),
		tag(8, 3),
		tag(9, {"Move on now!", "Moonlight destiny", "Precious"}),
		tag(10, "ささかま リス子"),
		tag(11, "Tristar", "STAR☆ANIS", "WM"),
		tag(3, "09/18"),
	},
	{
		tag(1, "夏樹 みくる"), name_rm = "Mikuru",
		tag(2, "洲崎 綾"),
		tag(4, 3),
		tag(5, "アイスクリーム", "ソーダ"),
		tag(6, "ガーデニング", "洋服のリメイク", "サーフィン"),
		tag(7, "ViVid Kiss"),
		tag(8, 2),
		tag(9, {"オトナモード"}),
		tag(10, "巴山 萌菜"),
		tag(11, "WM"),
		tag("pets", "フェレッ太"),
		tag(3, "07/07"),
	},
	{
		tag(1, "藤原 みやび"), name_rm = "Miyabi",
		tag(2, "関根 明良"),
		tag(4, 2),
		tag(5, "お漬物", "抹茶スイーツ"),
		tag(6, "着付け", "薙刀"),
		tag(7, "桜色花伝"),
		tag(8, 2),
		tag(9, {"薄紅デイトリッパー"}),
		tag(10, "美谷 玲美"),
		tag(11, "あまふわ☆なでしこ"),
		tag(12, "姫桜女学院"),
		tag(3, "09/14"),
	},
	{
		tag(1, "栗栖 ここね"), name_rm = "Kokone",
		tag(2, "伊藤星咲 花那恵"),
		tag(4, 1),
		tag(5, "シャテーニュロール", "オムレツ"),
		tag(6, "四葉のクローバーをみつけること"),
		tag(7, "Retro Clover"),
		tag(8, 2),
		tag(9, {"Sweet Heart Restaurant"}),
		tag(10, "愛野 えり"),
		tag(11, "あまふわ☆なでしこ"),
		tag(12, "エトワール学院"),
		tag(3, "08/21"),
	},
	{
		tag(1, "白樺 リサ"), name_rm = "Lisa",
		tag(2, "福 沙奈恵"),
		tag(4, 1),
		tag(5, "ポテトサラダ", "牛乳"),
		tag(6, "勉強", "編み物"),
		tag(7, "Dollydevil"),
		tag(8, 3),
		tag(10, "松岡 ななせ"),
		tag(12, 1),
		tag(3, "12/14"),
	},
	{
		tag(1, "大地 のの"), name_rm = "Nono",
		tag(2, "小岩井 ことり"),
		tag(4, 3),
		tag(5, "肉じゃが", "牛乳", "ほしいも"),
		tag(6, "カラオケ"),
		tag(7, "Dollydevil"),
		tag(8, 3),
		tag(10, "天音 みほ"),
		tag(12, 1),
		tag(3, "01/10"),
	},
	{
		tag(1, "堂島 ニーナ"), name_rm = "Nina",
		tag(2, "矢野 亜沙美"),
		tag(4, 4),
		tag(5, "たこやき", "おこのみやき"),
		tag(6, "おわらい", "絵を描くこと"),
		tag(7, "Mecha PaniQ"),
		tag(8, 2),
		tag(10, "星咲 花那"),
		tag(12, "なにわ天下一学苑"),
		tag(3, "02/07"),
	},
	{
		tag(1, "花輪 やよい"), name_rm = "Yayoi",
		tag(2, "上田 麗奈"),
		tag(4, 2),
		tag(5, "おにぎり", "いぶりがっこ", "甘酒"),
		tag(6, "太鼓"),
		tag(7, "MAGICAL TOY"),
		tag(8, 2),
		tag(12, "小町女学院"),
		tag(3, "12/18"),
	},
	{
		tag(1, "波照間 みなみ"), name_rm = "Minami",
		tag(2, "藤田 茜"),
		tag(4, 1),
		tag(5, "ゴーヤチャンプルー", "ソーキそば"),
		tag(6, "ダンス"),
		tag(7, "Dance Fusion"),
		tag(8, 4),
		tag(12, "美ら海ビートアカデミー"),
		tag(3, "08/22"),
	}
}, {__mode = "k"})

