local type
local cute, cool, sexy, pop = "Cute", "Cool", "Sexy", "Pop"
local Star_Anis = {Waka = "霧島 若歌", Furi = "上花楓裏", Risuko = "さかさまリス子", Remi = "美谷 玲美", Eri = "愛野 えり", Yuna = "市倉 有菜"}
local Aikatsu_Stars = {}


return setmetatable({
	{
		{"name", "星宮 いちご"},
		name_rm = "Ichigo",
		{"actor", "諸星 すみれ"},
		{"birthday", "03/15"},
		{"zodiac_sign", "Picces"},
		{"blood_type", "O"},
		{"favorite_foods", {"のり弁"}},
		{"special_ablity", {"ご飯をきっちりよそう"}},
		{"favorite_brand", "Angely Sugar"},
		{"type", cute},
		{"signature_songs", {"輝きのエチュード", "Growing for a dream", "Dance in the rain"}},
		{"sing", "霧島 若歌"},
		{"affilication", {"Soleil", "STAR☆ANIS", "2wingS"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "霧矢 あおい"},
		name_rm = "Aoi",
		{"actor", "田所 あずさ"},
		{"birthday", "01/31"},
		{"zodiac_sign", "Aquarius"},
		{"blood_type", "A"},
		{"favorite_foods", {"サンドイッチ"}},
		{"special_ablity", {"一目見たアイドルは忘れない"}},
		{"favorite_brand", "FUTURING GIRL"},
		{"type", cool},
		{"signature_songs", {"prism spiral", "Stranger alien"}},
		{"sing", "上花 風裏"},
		{"affilication", {"Soleil", "STAR☆ANIS"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "紫吹 蘭"},
		name_rm = "Ran",
		{"actor", "大橋 彩香"},
		{"birthday", "08/03"},
		{"zodiac_sign", "Leo"},
		{"blood_type", "AB"},
		{"favorite_foods", {"野菜スティック", "ヨーグルト"}},
		{"special_ablity", {"ウォーキング", "ポージング"}},
		{"favorite_brand", "SPICY AGEHA"},
		{"type", sexy},
		{"signature_songs", {"Trap of Love"}},
		{"sing", "市倉 有菜"},
		{"affilication", {"Soleil", "Tristar", "STAR☆ANIS"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "神谷 しおん"},
		name_rm = "Shion",
		{"actor", "瀬戸 麻沙美"},
		{"birthday", "01/11"},
		{"zodiac_sign", "Capricorn"},
		{"blood_type", "A"},
		{"favorite_foods", {"ガトーショコラ"}},
		-- {"special_ablity", {""}},
		{"favorite_brand", "FUTURING GIRL"},
		{"type", cool},
		{"affilication", {"ぽわぽわプリリン"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "有栖川 おとめ"},
		name_rm = "Otome",
		{"actor", "黒沢 ともよ"},
		{"birthday", "05/05"},
		{"zodiac_sign", "Taurus"},
		{"blood_type", "B"},
		{"favorite_foods", {"ハンバーグ", "オムライス", "スパゲッティ", "エビフライ", "プリン"}},
		{"special_ablity", {"動物のモノマネ"}},
		{"favorite_brand", "HAPPY RAINBOW"},
		{"type", pop},
		{"signature_songs", {"Angel Snow", "放課後ポニーテール", "CHU-CHU RAINBOW"}},
		{"sing", "美谷 玲美"},
		{"affilication", {"ぽわぽわプリリン", "STAR☆ANIS"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "藤堂 ユリカ"},
		name_rm = "Yurika",
		{"actor", "沼倉 愛美"},
		{"birthday", "12/26"},
		{"zodiac_sign", "Capricorn"},
		{"blood_type", "B"},
		{"favorite_foods", {"牛丼", "ラーメン"}},
		{"special_ablity", {"水泳"}},
		{"favorite_brand", "LoLi GoThiC"},
		{"type", cool},
		{"signature_songs", {"硝子ドール", "永遠の灯"}},
		{"sing", "美谷 玲美"},
		{"affilication", {"Tristar", "STAR☆ANIS"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "北大路 さくら"},
		name_rm = "Sakura",
		{"actor", "安野 希世乃"},
		{"birthday", "04/06"},
		{"zodiac_sign", "Aries"},
		{"blood_type", "A"},
		{"favorite_foods", {"抹茶", "和菓子"}},
		{"special_ablity", {"特に何も"}},
		{"favorite_brand", "Aurora Fantasy"},
		{"type", cute},
		{"signature_songs", {"同じ地球のしあわせに"}},
		{"affilication", {"ぽわぽわプリリン", "STAR☆ANIS"}},
		{"sing", "愛野 えり"},
		{"school", "スターライト学園"},
		{"pet", {"koiichi", "koini", "koisan", "koishi", "koigo", "koiroku"}},
	},
	{
		{"name", "一ノ瀬 かえで"},
		name_rm = "Kaede",
		{"actor", "三村 ゆうな"},
		{"birthday", "11/23"},
		{"zodiac_sign", "Sagittarius"},
		{"blood_type", "O"},
		{"favorite_foods", {"カリフォルニアロール", "ハンバーガー"}},
		{"special_ablity", {"マジック", "ダンス全般"}},
		{"favorite_brand", "MAGICAL TOY"},
		{"type", pop},
		{"sing", "市倉 有菜"},
		{"affilication", {"Tristar", "STAR☆ANIS"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "三ノ輪 ヒカリ"},
		name_rm = "Hikari",
		{"actor", "森谷 里美"},
		{"birthday", "03/28"},
		{"zodiac_sign", "Aries"},
		{"blood_type", "AB"},
		{"favorite_foods", {"トロピカルジュース", "ロコモコ"}},
		-- {"special_ablity", }
		{"favorite_brand", "SPICY AGEHA"},
		{"type", sexy},
		{"sing", "森下 ゆにこ"},
		{"school", "スターライト学園"},
	},
	{
		{"name", "大空 あかり"},
		name_rm = "Akari",
		{"actor", "下地 柴野"},
		{"birthday", "04/01"},
		{"zodiac_sign", "Aries"},
		{"blood_type", "A"},
		{"favorite_foods", {"スイカ", "チョコレート", "ドーナツ", "みかん", "カレー"}},
		{"special_ablity", "ものまね"},
		{"favorite_brand", "Dreamy Crown"},
		{"type", cute},
		{"signature_songs", {}},
		{"sing", "遠藤 瑠香"},
		{"affilication", {"GOGO! いちご応援隊"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "氷上 スミレ"},
		name_rm = "Sumire",
		{"actor", "和久井 優"},
		{"birthday", "10/20"},
		{"zodiac_sign", "Libra"},
		{"blood_type", "AB"},
		{"favorite_foods", {"紅茶", "スコーン"}},
		{"special_ablity", {"タロット占い"}},
		{"favorite_brand", "LoLi GoThiC"},
		{"type", cool},
		{"signature_songs", {"タルト･タタン"}},
		{"sing", "巴山 萌菜"},
		{"affilication", {"GOGO! いちご応援隊"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "新条 ひなき"},
		name_rm = "Hinaki",
		{"actor", "石川 由依"},
		{"birthday", "06/11"},
		{"zodiac_sign", "Gemini"},
		{"blood_type", "B"},
		{"favorite_foods", {"ビタミンCドリンク", "グレープフルーツ", "アサイー"}},
		{"special_ablity", {"美の追求", "情報収集", "新ブランドなどのニュース集め"}},
		{"favorite_brand", "ViVid Kiss"},
		{"type", pop},
		{"sing", "みき"},
		{"affilication", {"GOGO! いちご応援隊"}},
		{"school", "スターライト学園"},
	},
	{
		{"name", "紅林 珠璃"},
		name_rm = "Juri",
		{"actor", "斎藤 綾"},
		{"birthday", "07/31"},
		{"zodiac_sign", "Leo"},
		{"blood_type", "O"},
		{"favorite_foods", {"生ハム", "パエリア"}},
		{"special_ablity", {"フラメンコ", "バレエ"}},
		{"favorite_brand", "Sangria Rosa"},
		{"type", sexy},
		{"signature_songs", {"Passion Flower"}},
		{"sing", "みほ"},
		{"school", "スターライト学園"},
	},
	{
		{"name", "黒沢 凛"},
		name_rm = "Rin",
		{"actor", "高田 憂希"},
		{"birthday", "01/01"},
		{"zodiac_sign", "Capricorn"},
		{"blood_type", "AB"},
		{"favorite_foods", {"しらたまあんみつ", "からあげ"}},
		{"special_ablity", {"ダンス"}},
		{"favorite_brand", "Dance Fusion"},
		{"type", cool},
		{"signature_songs", {"MY SHOW TIME!"}},
		{"sing", "ななせ"},
		{"school", "スターライト学園"}
	},
	{
		{"name", "天羽 まどか"},
		name_rm = "Madoka",
		{"actor", "川上 千尋"},
		{"birthday", "02/14"},
		{"zodiac_sign", "Aquarius"},
		{"blood_type", "O"},
		{"favorite_foods", {"チョコレート"}},
		{"special_ablity", {"スマイル"}},
		{"favorite_brand", "Angely Sugar"},
		{"type", cute},
		{"signature_songs", {"ハローニューワールド"}},
		{"sing", "かな"},
		{"school", "スターライト学園"}
	},

	-- Dream Academy
	{
		{"name", "音城 セイラ"},
		name_rm = "Seira",
		{"actor", "石原 夏織"},
		{"birthday", "11/11"},
		{"zodiac_sign", "Scorpio"},
		{"blood_type", "A"},
		{"favorite_foods", {"パスタ", "コーヒーゼリー"}},
		{"special_ablity", {"学期全般"}},
		{"favorite_brand", "Swing ROCK"},
		{"type", cool},
		{"sing", "上花 風裏"},
		{"affilication", {"2wingS"}},
		{"school", "ドリーム・アカデミー"},
	},
	{
		{"name", "冴草 きい"},
		name_rm = "Kii",
		{"actor", "秋奈"},
		{"birthday", "12/03"},
		{"zodiac_sign", "Sagittarius"},
		{"blood_type", "O"},
		{"favorite_foods", {"ブレインサンダー"}},
		{"special_ablity", {"パソコン"}},
		{"favorite_brand", "MAGICAL TOY"},
		{"type", pop},
		{"signature_songs", {"マジカルタイム"}},
		{"sing", "市倉 有菜"},
		{"school", "ドリーム・アカデミー"},
	},
	{
		{"name", "風沢 そら"},
		name_rm = "Sora",
		{"actor", "高橋 未奈美"},
		{"birthday", "10/02"},
		{"zodiac_sign", "Libra"},
		{"blood_type", "B"},
		{"favorite_foods", {"エスニック料理全般"}},
		{"special_ablity", {"ドレスデザイン", "一人旅"}},
		{"favorite_brand", "Bohemian Sky"},
		{"type", sexy},
		{"signature_songs", {"Kira･pata･shining"}},
		{"sing", "愛野 えり"},
		{"school", "ドリーム・アカデミー"},
		{"pet", "パーム"},
	},
	{
		{"name", "姫里 マリア"},
		name_rm = "Maria",
		{"actor", "冨岡 美沙子"},
		{"birthday", "04/18"},
		{"zodiac_sign", "Virgo"},
		{"blood_type", "O"},
		{"favorite_foods", {"ザッハトルテ"}},
		{"special_ablity", {"違いのわかる女!"}},
		{"favorite_brand", "Aurora Fantasy"},
		{"type", cute},
		{"signature_songs", {"オーロラプリンセス"}},
		{"sing", "愛野 えり"},
		{"school", "ドリーム・アカデミー"},
		{"pet", "エリザベス三世"},
	},

	-- other
	{
		{"name", "神崎 美月"},
		name_rm = "Mizuki",
		{"actor", "寿 美菜子"},
		{"birthday", "09/18"},
		{"zodiac_sign", "Virgo"},
		{"blood_type", "A"},
		{"favorite_foods", {"マロングラッセ", "香りの良い紅茶"}},
		{"special_ablity", {"歌"}},
		{"favorite_brand", "LOVE MOONRISE"},
		{"type", sexy},
		{"signature_songs", {"Move on now!", "Moonlight destiny", "Precious"}},
		{"sing", "ささかま リス子"},
		{"affilication", {"Tristar", "STAR☆ANIS", "WM"}},
	},
	{
		{"name", "夏樹 みくる"},
		name_rm = "Mikuru",
		{"actor", "洲崎 綾"},
		{"birthday", "07/07"},
		{"zodiac_sign", "Cancer"},
		{"blood_type", "O"},
		{"favorite_foods", {"アイスクリーム", "ソーダ"}},
		{"special_ablity", {"ガーデニング", "洋服のリメイク", "サーフィン"}},
		{"favorite_brand", "ViVid Kiss"},
		{"type", pop},
		{"signature_songs", {"オトナモード"}},
		{"sing", "巴山 萌菜"},
		{"affilication", {"WM"}},
		{"pet", "フェレッ太"},
	},
	{
		{"name", "藤原 みやび"},
		name_rm = "Miyabi",
		{"actor",  "関根明良"},
		{"birthday", "09/14"},
		{"zodiac_sign", "Virgo"},
		{"blood_type", "B"},
		{"favorite_foods", {"お漬物", "抹茶スイーツ"}},
		{"special_ablity", {"着付け", "薙刀"}},
		{"favorite_brand", "桜色花伝"},
		{"type", sexy},
		{"signature_songs", {"薄紅デイトリッパー"}},
		{"sing", "美谷 玲美"},
		{"school", "姫桜女学院"}
	}
}, {__mode = "k"})

